@echo off
REM Mobile Testing Setup Script for Rabab Complex Stay (Windows)

echo 📱 Setting up mobile testing for Rabab Complex Stay...
echo.

REM Get local IP
echo 🔍 Finding your local IP address...
cd frontend
node scripts/get-network-ip.js > temp-ip.txt

REM Parse IP from output
for /f "tokens=2 delims=: " %%a in ('findstr /C:"address" temp-ip.txt') do (
    set IP=%%a
    goto :found
)

:found
del temp-ip.txt

if "%IP%"=="" (
    echo ❌ Could not detect IP address. Please check your network connection.
    pause
    exit /b 1
)

echo ✅ Found IP: %IP%
echo.

REM Create .env file
echo 📝 Creating frontend/.env file...
(
echo # Mobile testing configuration
echo # Auto-generated by setup-mobile.bat
echo VITE_API_BASE_URL=http://%IP%:5000/api
) > .env

echo ✅ Created frontend/.env with IP: %IP%
echo.

echo 🎉 Setup complete!
echo.
echo 📋 Next steps:
echo 1. Start backend:  cd backend ^&^& npm run dev
echo 2. Start frontend: cd frontend ^&^& npm run dev:mobile
echo 3. Open on mobile: http://%IP%:5173
echo.
echo 💡 Tip: Make sure your phone is on the same Wi-Fi network!
echo.
pause
