#!/bin/bash

# Mobile Testing Setup Script for Rabab Complex Stay

echo "📱 Setting up mobile testing for Rabab Complex Stay..."
echo ""

# Get local IP
echo "🔍 Finding your local IP address..."
cd frontend
IP=$(node scripts/get-network-ip.js | grep -oP '\d+\.\d+\.\d+\.\d+' | head -1)

if [ -z "$IP" ]; then
    echo "❌ Could not detect IP address. Please check your network connection."
    exit 1
fi

echo "✅ Found IP: $IP"
echo ""

# Create .env file
echo "📝 Creating frontend/.env file..."
cat > .env << EOF
# Mobile testing configuration
# Auto-generated by setup-mobile.sh
VITE_API_BASE_URL=http://$IP:5000/api
EOF

echo "✅ Created frontend/.env with IP: $IP"
echo ""

echo "🎉 Setup complete!"
echo ""
echo "📋 Next steps:"
echo "1. Start backend:  cd backend && npm run dev"
echo "2. Start frontend: cd frontend && npm run dev:mobile"
echo "3. Open on mobile: http://$IP:5173"
echo ""
echo "💡 Tip: Make sure your phone is on the same Wi-Fi network!"
